# Generated by Django 4.2.7 on 2023-12-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('recruiter_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('recruiter_email', models.EmailField(max_length=254)),
            ],
        ),
    ]
